set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT[3]}]
set_property PACKAGE_PIN U21 [get_ports {OUT[3]}]
set_property PACKAGE_PIN U22 [get_ports {OUT[2]}]
set_property PACKAGE_PIN T21 [get_ports {OUT[1]}]
set_property PACKAGE_PIN T22 [get_ports {OUT[0]}]
set_property PACKAGE_PIN T18 [get_ports CLK]
set_property PACKAGE_PIN R18 [get_ports RESET]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF] 

